#!/bin/bash

set -o errexit

MSYS_NO_PATHCONV=1 subst /d a: | true && subst a: .

history -c
export HISTFILE=/a/local/.bash_history

export PATH=/a/scripts:$PATH
export PATH=/a/scripts/msvc:$PATH

code /a --reuse-window
