#!/bin/bash

set -o errexit

#

path=$( pwd )
root=${path#/}
root=/${root%%/*}
[[ $root == /a ]] || MSYS_NO_PATHCONV=1 subst /d a: | true && subst a: .

#

history -c
export HISTFILE=/a/local/.bash_history

#

export PATH=/a/scripts:$PATH

#

code /a --reuse-window
