#!/bin/bash

set -o errexit

rm --recursive --force local/build
mkdir --parents        local/build
cd                     local/build

# clang

# clang -Wall -Wextra /a/source/main.cpp --output main.exe

# msvc

source msvc.sh
cl a:/source/main.cpp -nologo -GR- -Wall -WX -link -entry:mainCRTStartup -out:main.exe
